line-length = 100
target-version = "py312"
extend-exclude = [
  "test",
  "scripts",
  "tools",
  "migrations",
  "../temp",
]

[lint]
select = ["E", "F", "I", "B"]
ignore = ["B008", "E501"]

[format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"
