from __future__ import annotations

from app.crud.human_resources.dashboard_legacy import (
    _build_insurance_employee_master_index,
    _normalize_period_to_month_key,
    _social_metric_payload,
    _year_months,
)
from app.crud.human_resources.dashboard_scope import list_scope_orgs, normalize_scope

from .aggregate_store import _load_aggregate_rows, _store_aggregate_rows
from .archive_snapshot import (
    get_employee_archive_options,
    list_employee_archive_change_logs,
    list_employee_archives,
    refresh_employee_archive_snapshot,
    update_employee_archive,
)
from .daily_shared import _insurance_orgs_for_scope
from .facts import (
    create_performance_fact,
    create_salary_welfare_fact,
    get_performance_fact,
    get_salary_welfare_fact,
    list_manual_recruitment_entries,
    list_performance_facts,
    list_salary_welfare_facts,
    serialize_manual_recruitment_entry,
    serialize_performance_fact,
    serialize_salary_welfare_fact,
    upsert_manual_recruitment_entry,
    update_performance_fact,
    update_salary_welfare_fact,
)
from .refresh import (
    is_dashboard_dirty,
    mark_dashboard_for_values,
    mark_scope_dashboard_dirty,
    process_dashboard_refresh_for_values,
    process_scope_dashboard_chain_refresh,
    refresh_dashboard_for_values,
    refresh_scope_dashboard_chain,
    rebuild_daily_dashboard,
    rebuild_monthly_dashboard,
    rebuild_yearly_dashboard,
    run_pending_dashboard_refreshes,
)
from .rollups import (
    build_daily_dashboard,
    build_monthly_dashboard,
    build_yearly_dashboard,
    read_daily_dashboard,
    read_monthly_dashboard,
    read_yearly_dashboard,
)

__all__ = [
    "_load_aggregate_rows",
    "_build_insurance_employee_master_index",
    "_insurance_orgs_for_scope",
    "_normalize_period_to_month_key",
    "_social_metric_payload",
    "_store_aggregate_rows",
    "_year_months",
    "build_daily_dashboard",
    "build_monthly_dashboard",
    "build_yearly_dashboard",
    "create_performance_fact",
    "create_salary_welfare_fact",
    "get_employee_archive_options",
    "list_employee_archive_change_logs",
    "get_performance_fact",
    "get_salary_welfare_fact",
    "is_dashboard_dirty",
    "list_employee_archives",
    "list_manual_recruitment_entries",
    "list_performance_facts",
    "list_salary_welfare_facts",
    "mark_dashboard_for_values",
    "mark_scope_dashboard_dirty",
    "list_scope_orgs",
    "normalize_scope",
    "process_dashboard_refresh_for_values",
    "process_scope_dashboard_chain_refresh",
    "read_daily_dashboard",
    "read_monthly_dashboard",
    "read_yearly_dashboard",
    "refresh_dashboard_for_values",
    "refresh_employee_archive_snapshot",
    "refresh_scope_dashboard_chain",
    "rebuild_daily_dashboard",
    "rebuild_monthly_dashboard",
    "rebuild_yearly_dashboard",
    "run_pending_dashboard_refreshes",
    "serialize_manual_recruitment_entry",
    "serialize_performance_fact",
    "serialize_salary_welfare_fact",
    "update_employee_archive",
    "update_performance_fact",
    "update_salary_welfare_fact",
    "upsert_manual_recruitment_entry",
]
